#!/bin/bash
DIR=$(dirname $0)
DICT=$DIR/croco-dict.txt
HISTORY=$DIR/croco-history.txt
BADWORDS=$DIR/croco-badwords.txt

theword=$(grep -v -f $HISTORY -f $BADWORDS $DICT | shuf -n1)
echo "$theword" >> $HISTORY
echo "$theword"

